Modul 6
Danik2021/JavaScript pull request #4
Opened 2024-10-22 12:20 UTC by Danik2021

2024-10-25 09:09 UTC, xrustic2020 requested changes

2024-10-25 09:09 UTC, xrustic2020 commented on js/task-02.js
> +  ingredientsListEl.append(itemEl);
В завданні треба додати в html всі елементи за один раз)
А не на кожну ітерацію пхати по одному елементу)

2024-10-25 09:09 UTC, xrustic2020 commented on js/task-02.js
> +  ingredientsListEl.append(itemEl);
Це важливо, бо виходить браузер буде перемальовувати сторінку стільки разів, стільки ти append зробиш. Важливо щоб такі перемалювання (repaint) відбувалися якомога менше, щоб в користувача твого сайту не дьоргався контент на кожний елемент списку)

2024-10-25 09:09 UTC, xrustic2020 commented on js/task-03.js
> +});
Знову додаєш контент на кожну ітерацію, А треба спочатку все в скрипті підготував, А вже потім все за одну операцію додав в html

2024-10-25 09:09 UTC, xrustic2020 commented on task-01.html
> +<!-- <script src="./training/scripts.js"></script> -->
Прибери зайвий код. Цього не має бути в ПРі

2024-10-25 11:36 UTC, Danik2021 commented on js/task-02.js
> +  ingredientsListEl.append(itemEl);
✅ ✅ ✅

2024-10-25 13:42 UTC, Danik2021 commented on js/task-03.js
> +});
✅ ✅ ✅

2024-10-25 13:42 UTC, Danik2021 commented on task-01.html
> +<!-- <script src="./training/scripts.js"></script> -->
✅ ✅ ✅

2024-10-26 09:13 UTC, xrustics commented on js/task-02.js
> +const ingredientsItemsEl = [];
а чи треба нам новий массив створювати?

що можна замість forEach інше використати, що поверне новий масив?)

2024-10-26 09:13 UTC, xrustic2020 commented on js/task-02.js
> +const ingredientsItemsEl = [];
map тобі в допомогу)

2024-10-26 09:13 UTC, xrustic2020 commented on js/task-03.js
> +  .map(({ url, alt }) => `<li><img src=${url} alt=${alt}></li>`)
подумай як ще можна зробити в результаті стрічку з тегами тільки меншої кількістю циклів?
виходить зараз ти проходиш по массиву двічі, перший раз map проходить, а другий join.

як зробити, щоб пройти один раз по масиву та в результаті зібрати стрічку с тегами?)
так і зроби)

2024-11-05 16:54 UTC, xrustic2020 commented on js/task-02.js
> +const ingredientsItemsEl = [];
тут ще не оновив)

2024-11-05 16:54 UTC, xrustic2020 commented on js/task-03.js
> +  .map(({ url, alt }) => `<li><img src=${url} alt=${alt}></li>`)
тут теж ще не оновив

2024-11-11 16:50 UTC, merged